// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/natural_resource_management.proto

package nrm

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Replaceable update
//
// Fields given as an example
type GenericUpdate struct {
	Units                int32                `protobuf:"varint,1,opt,name=units,proto3" json:"units,omitempty"`
	Start                *timestamp.Timestamp `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	Finish               *timestamp.Timestamp `protobuf:"bytes,3,opt,name=finish,proto3" json:"finish,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *GenericUpdate) Reset()         { *m = GenericUpdate{} }
func (m *GenericUpdate) String() string { return proto.CompactTextString(m) }
func (*GenericUpdate) ProtoMessage()    {}
func (*GenericUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf1e0482166d86ce, []int{0}
}

func (m *GenericUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenericUpdate.Unmarshal(m, b)
}
func (m *GenericUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenericUpdate.Marshal(b, m, deterministic)
}
func (m *GenericUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenericUpdate.Merge(m, src)
}
func (m *GenericUpdate) XXX_Size() int {
	return xxx_messageInfo_GenericUpdate.Size(m)
}
func (m *GenericUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_GenericUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_GenericUpdate proto.InternalMessageInfo

func (m *GenericUpdate) GetUnits() int32 {
	if m != nil {
		return m.Units
	}
	return 0
}

func (m *GenericUpdate) GetStart() *timestamp.Timestamp {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *GenericUpdate) GetFinish() *timestamp.Timestamp {
	if m != nil {
		return m.Finish
	}
	return nil
}

// Summary of the storage operation
type StorageSummary struct {
	Success              bool                 `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Attempts             int32                `protobuf:"varint,2,opt,name=attempts,proto3" json:"attempts,omitempty"`
	LastAttemptedAt      *timestamp.Timestamp `protobuf:"bytes,3,opt,name=last_attempted_at,json=lastAttemptedAt,proto3" json:"last_attempted_at,omitempty"`
	FailureMessage       string               `protobuf:"bytes,4,opt,name=failure_message,json=failureMessage,proto3" json:"failure_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *StorageSummary) Reset()         { *m = StorageSummary{} }
func (m *StorageSummary) String() string { return proto.CompactTextString(m) }
func (*StorageSummary) ProtoMessage()    {}
func (*StorageSummary) Descriptor() ([]byte, []int) {
	return fileDescriptor_bf1e0482166d86ce, []int{1}
}

func (m *StorageSummary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageSummary.Unmarshal(m, b)
}
func (m *StorageSummary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageSummary.Marshal(b, m, deterministic)
}
func (m *StorageSummary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageSummary.Merge(m, src)
}
func (m *StorageSummary) XXX_Size() int {
	return xxx_messageInfo_StorageSummary.Size(m)
}
func (m *StorageSummary) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageSummary.DiscardUnknown(m)
}

var xxx_messageInfo_StorageSummary proto.InternalMessageInfo

func (m *StorageSummary) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *StorageSummary) GetAttempts() int32 {
	if m != nil {
		return m.Attempts
	}
	return 0
}

func (m *StorageSummary) GetLastAttemptedAt() *timestamp.Timestamp {
	if m != nil {
		return m.LastAttemptedAt
	}
	return nil
}

func (m *StorageSummary) GetFailureMessage() string {
	if m != nil {
		return m.FailureMessage
	}
	return ""
}

func init() {
	proto.RegisterType((*GenericUpdate)(nil), "nrm.GenericUpdate")
	proto.RegisterType((*StorageSummary)(nil), "nrm.StorageSummary")
}

func init() {
	proto.RegisterFile("protos/natural_resource_management.proto", fileDescriptor_bf1e0482166d86ce)
}

var fileDescriptor_bf1e0482166d86ce = []byte{
	// 308 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x51, 0xb1, 0x4e, 0xeb, 0x40,
	0x10, 0x7c, 0xf7, 0x82, 0x43, 0x38, 0x44, 0x22, 0x0e, 0x0a, 0xe3, 0x86, 0x28, 0x0d, 0xae, 0x9c,
	0x28, 0x48, 0xf4, 0x69, 0xa0, 0x0a, 0x85, 0x03, 0xb5, 0xb5, 0x71, 0x36, 0xc6, 0x92, 0xef, 0x6c,
	0xdd, 0xee, 0x15, 0x7c, 0x03, 0x1f, 0xc4, 0xef, 0xa1, 0xf8, 0xec, 0x48, 0xa9, 0xa0, 0x9c, 0xd1,
	0xcc, 0x68, 0x76, 0x47, 0xc6, 0x8d, 0xad, 0xb9, 0xa6, 0xb9, 0x01, 0x76, 0x16, 0xaa, 0xcc, 0x22,
	0xd5, 0xce, 0xe6, 0x98, 0x69, 0x30, 0x50, 0xa0, 0x46, 0xc3, 0x49, 0x2b, 0x51, 0x03, 0x63, 0x75,
	0x74, 0x5f, 0xd4, 0x75, 0x51, 0xe1, 0xbc, 0xa5, 0xb6, 0x6e, 0x3f, 0xe7, 0x52, 0x23, 0x31, 0xe8,
	0xc6, 0xab, 0x66, 0x5f, 0x42, 0x5e, 0xbd, 0xa0, 0x41, 0x5b, 0xe6, 0xef, 0xcd, 0x0e, 0x18, 0xd5,
	0xad, 0x0c, 0x9c, 0x29, 0x99, 0x42, 0x31, 0x15, 0x71, 0x90, 0x7a, 0xa0, 0x16, 0x32, 0x20, 0x06,
	0xcb, 0xe1, 0xff, 0xa9, 0x88, 0x2f, 0x97, 0x51, 0xe2, 0x83, 0x93, 0x3e, 0x38, 0x79, 0xeb, 0x83,
	0x53, 0x2f, 0x54, 0x4b, 0x39, 0xdc, 0x97, 0xa6, 0xa4, 0x8f, 0x70, 0xf0, 0xab, 0xa5, 0x53, 0xce,
	0xbe, 0x85, 0x1c, 0x6f, 0xb8, 0xb6, 0x50, 0xe0, 0xc6, 0x69, 0x0d, 0xf6, 0x53, 0x85, 0xf2, 0x9c,
	0x5c, 0x9e, 0x23, 0xf9, 0x42, 0xa3, 0xb4, 0x87, 0x2a, 0x92, 0x23, 0x60, 0x46, 0xdd, 0x30, 0xb5,
	0xad, 0x82, 0xf4, 0x88, 0xd5, 0xb3, 0xbc, 0xae, 0x80, 0x38, 0xeb, 0x08, 0xdc, 0x65, 0xc0, 0x7f,
	0xe8, 0x31, 0x39, 0x98, 0x56, 0xbd, 0x67, 0xc5, 0xea, 0x41, 0x4e, 0xf6, 0x50, 0x56, 0xce, 0x62,
	0xa6, 0x91, 0x08, 0x0a, 0x0c, 0xcf, 0xa6, 0x22, 0xbe, 0x48, 0xc7, 0x1d, 0xbd, 0xf6, 0xec, 0x72,
	0x23, 0xef, 0x5e, 0xfd, 0x24, 0x69, 0xb7, 0xc8, 0xfa, 0x38, 0x88, 0x7a, 0x92, 0xc1, 0xe1, 0x2a,
	0x54, 0x2a, 0x31, 0x56, 0x27, 0x27, 0xff, 0x8e, 0x6e, 0x5a, 0xee, 0xf4, 0xea, 0xd9, 0xbf, 0x58,
	0x2c, 0xc4, 0x76, 0xd8, 0x56, 0x7c, 0xfc, 0x09, 0x00, 0x00, 0xff, 0xff, 0x15, 0xbf, 0x17, 0x79,
	0xf5, 0x01, 0x00, 0x00,
}
