// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/generic/natural_resource_management.proto

package nrm

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Replaceable update
//
// Fields given as an example
type ResourceUpdate struct {
	Units                int32                `protobuf:"varint,1,opt,name=units,proto3" json:"units,omitempty"`
	Start                *timestamp.Timestamp `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	Finish               *timestamp.Timestamp `protobuf:"bytes,3,opt,name=finish,proto3" json:"finish,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ResourceUpdate) Reset()         { *m = ResourceUpdate{} }
func (m *ResourceUpdate) String() string { return proto.CompactTextString(m) }
func (*ResourceUpdate) ProtoMessage()    {}
func (*ResourceUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_64cfcd1a34e44785, []int{0}
}

func (m *ResourceUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceUpdate.Unmarshal(m, b)
}
func (m *ResourceUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceUpdate.Marshal(b, m, deterministic)
}
func (m *ResourceUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceUpdate.Merge(m, src)
}
func (m *ResourceUpdate) XXX_Size() int {
	return xxx_messageInfo_ResourceUpdate.Size(m)
}
func (m *ResourceUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceUpdate proto.InternalMessageInfo

func (m *ResourceUpdate) GetUnits() int32 {
	if m != nil {
		return m.Units
	}
	return 0
}

func (m *ResourceUpdate) GetStart() *timestamp.Timestamp {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *ResourceUpdate) GetFinish() *timestamp.Timestamp {
	if m != nil {
		return m.Finish
	}
	return nil
}

// Summary of the storage operation
type StorageSummary struct {
	Success              bool                 `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Attempts             int32                `protobuf:"varint,2,opt,name=attempts,proto3" json:"attempts,omitempty"`
	LastAttemptedAt      *timestamp.Timestamp `protobuf:"bytes,3,opt,name=last_attempted_at,json=lastAttemptedAt,proto3" json:"last_attempted_at,omitempty"`
	FailureMessage       string               `protobuf:"bytes,4,opt,name=failure_message,json=failureMessage,proto3" json:"failure_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *StorageSummary) Reset()         { *m = StorageSummary{} }
func (m *StorageSummary) String() string { return proto.CompactTextString(m) }
func (*StorageSummary) ProtoMessage()    {}
func (*StorageSummary) Descriptor() ([]byte, []int) {
	return fileDescriptor_64cfcd1a34e44785, []int{1}
}

func (m *StorageSummary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageSummary.Unmarshal(m, b)
}
func (m *StorageSummary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageSummary.Marshal(b, m, deterministic)
}
func (m *StorageSummary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageSummary.Merge(m, src)
}
func (m *StorageSummary) XXX_Size() int {
	return xxx_messageInfo_StorageSummary.Size(m)
}
func (m *StorageSummary) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageSummary.DiscardUnknown(m)
}

var xxx_messageInfo_StorageSummary proto.InternalMessageInfo

func (m *StorageSummary) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *StorageSummary) GetAttempts() int32 {
	if m != nil {
		return m.Attempts
	}
	return 0
}

func (m *StorageSummary) GetLastAttemptedAt() *timestamp.Timestamp {
	if m != nil {
		return m.LastAttemptedAt
	}
	return nil
}

func (m *StorageSummary) GetFailureMessage() string {
	if m != nil {
		return m.FailureMessage
	}
	return ""
}

func init() {
	proto.RegisterType((*ResourceUpdate)(nil), "nrm.ResourceUpdate")
	proto.RegisterType((*StorageSummary)(nil), "nrm.StorageSummary")
}

func init() {
	proto.RegisterFile("protos/generic/natural_resource_management.proto", fileDescriptor_64cfcd1a34e44785)
}

var fileDescriptor_64cfcd1a34e44785 = []byte{
	// 349 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x51, 0xb1, 0x6e, 0xdb, 0x30,
	0x14, 0x2c, 0xeb, 0xca, 0x75, 0x59, 0xc0, 0x46, 0xd9, 0x0e, 0xaa, 0x96, 0x1a, 0x5e, 0xaa, 0xc5,
	0x92, 0xa0, 0x0e, 0x9d, 0x9d, 0x21, 0x9b, 0x33, 0xc8, 0xce, 0x92, 0x45, 0xa0, 0xe4, 0x67, 0x9a,
	0xb0, 0x48, 0x09, 0xe4, 0xe3, 0x90, 0x7f, 0xc8, 0xff, 0xe4, 0xf7, 0x02, 0x8b, 0x92, 0x01, 0x4f,
	0xc9, 0xc6, 0x77, 0xbc, 0x3b, 0xdc, 0x7b, 0x47, 0xb3, 0xce, 0xb4, 0xd8, 0xda, 0x54, 0x80, 0x06,
	0x23, 0xeb, 0x54, 0x73, 0x74, 0x86, 0x37, 0xa5, 0x01, 0xdb, 0x3a, 0x53, 0x43, 0xa9, 0xb8, 0xe6,
	0x02, 0x14, 0x68, 0x4c, 0x7a, 0x2a, 0x9b, 0x68, 0xa3, 0xa2, 0x3f, 0xa2, 0x6d, 0x45, 0x03, 0x69,
	0x0f, 0x55, 0xee, 0x98, 0xa2, 0x54, 0x60, 0x91, 0xab, 0xce, 0xb3, 0x56, 0x2f, 0x84, 0xce, 0x8b,
	0xc1, 0xe3, 0xb1, 0x3b, 0x70, 0x04, 0xf6, 0x8b, 0x06, 0x4e, 0x4b, 0xb4, 0x21, 0x59, 0x92, 0x38,
	0x28, 0xfc, 0xc0, 0x32, 0x1a, 0x58, 0xe4, 0x06, 0xc3, 0xcf, 0x4b, 0x12, 0x7f, 0xcf, 0xa3, 0xc4,
	0x3b, 0x27, 0xa3, 0x73, 0xb2, 0x1f, 0x9d, 0x0b, 0x4f, 0x64, 0x39, 0x9d, 0x1e, 0xa5, 0x96, 0xf6,
	0x14, 0x4e, 0xde, 0x95, 0x0c, 0xcc, 0xd5, 0x2b, 0xa1, 0xf3, 0x1d, 0xb6, 0x86, 0x0b, 0xd8, 0x39,
	0xa5, 0xb8, 0x79, 0x66, 0x21, 0xfd, 0x6a, 0x5d, 0x5d, 0x83, 0xf5, 0x81, 0x66, 0xc5, 0x38, 0xb2,
	0x88, 0xce, 0x38, 0x22, 0xa8, 0x0e, 0x6d, 0x9f, 0x2a, 0x28, 0xae, 0x33, 0xbb, 0xa7, 0x3f, 0x1a,
	0x6e, 0xb1, 0x1c, 0x00, 0x38, 0x94, 0x1c, 0x3f, 0x90, 0x63, 0x71, 0x11, 0x6d, 0x46, 0xcd, 0x06,
	0xd9, 0x5f, 0xba, 0x38, 0x72, 0xd9, 0x38, 0x03, 0xa5, 0x02, 0x6b, 0xb9, 0x80, 0xf0, 0xcb, 0x92,
	0xc4, 0xdf, 0x8a, 0xf9, 0x00, 0x6f, 0x3d, 0x9a, 0xef, 0xe9, 0xef, 0x07, 0xdf, 0xc9, 0x78, 0xce,
	0xed, 0xb5, 0x11, 0xf6, 0x9f, 0x06, 0x97, 0xad, 0x80, 0xfd, 0x4c, 0xb4, 0x51, 0xc9, 0xed, 0xc1,
	0x23, 0x0f, 0xde, 0xae, 0xbd, 0xfa, 0x14, 0x93, 0x8c, 0xdc, 0xe5, 0x4f, 0x99, 0x90, 0x78, 0x72,
	0x55, 0x52, 0xb7, 0x2a, 0xd5, 0x55, 0xc7, 0xcd, 0x19, 0x4c, 0xaa, 0x8d, 0x5a, 0x03, 0x9e, 0xd6,
	0x75, 0x23, 0x41, 0x63, 0xda, 0x9d, 0x85, 0x6f, 0xf8, 0xf2, 0x51, 0x4d, 0xfb, 0xe7, 0xbf, 0xb7,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xc9, 0x15, 0x4b, 0xf6, 0x33, 0x02, 0x00, 0x00,
}
