// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/fish/fish_capture_management.proto

package nrm

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FishType int32

const (
	FishType_NOT_SPECIFIED FishType = 0
	FishType_MACKEREL      FishType = 1
	FishType_SARDINE       FishType = 2
	FishType_COD           FishType = 3
	FishType_TUNA          FishType = 4
	FishType_RED_DRUM      FishType = 5
	FishType_BLUEFISH      FishType = 6
)

var FishType_name = map[int32]string{
	0: "NOT_SPECIFIED",
	1: "MACKEREL",
	2: "SARDINE",
	3: "COD",
	4: "TUNA",
	5: "RED_DRUM",
	6: "BLUEFISH",
}

var FishType_value = map[string]int32{
	"NOT_SPECIFIED": 0,
	"MACKEREL":      1,
	"SARDINE":       2,
	"COD":           3,
	"TUNA":          4,
	"RED_DRUM":      5,
	"BLUEFISH":      6,
}

func (x FishType) String() string {
	return proto.EnumName(FishType_name, int32(x))
}

func (FishType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7713465e1e636f0d, []int{0}
}

// Fish Resource Update
type ResourceUpdate struct {
	Fish                 []*Fish  `protobuf:"bytes,1,rep,name=fish,proto3" json:"fish,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResourceUpdate) Reset()         { *m = ResourceUpdate{} }
func (m *ResourceUpdate) String() string { return proto.CompactTextString(m) }
func (*ResourceUpdate) ProtoMessage()    {}
func (*ResourceUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_7713465e1e636f0d, []int{0}
}

func (m *ResourceUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceUpdate.Unmarshal(m, b)
}
func (m *ResourceUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceUpdate.Marshal(b, m, deterministic)
}
func (m *ResourceUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceUpdate.Merge(m, src)
}
func (m *ResourceUpdate) XXX_Size() int {
	return xxx_messageInfo_ResourceUpdate.Size(m)
}
func (m *ResourceUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceUpdate proto.InternalMessageInfo

func (m *ResourceUpdate) GetFish() []*Fish {
	if m != nil {
		return m.Fish
	}
	return nil
}

type Fish struct {
	WeightKg             int64                `protobuf:"varint,1,opt,name=weight_kg,json=weightKg,proto3" json:"weight_kg,omitempty"`
	Time                 *timestamp.Timestamp `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	Type                 FishType             `protobuf:"varint,3,opt,name=type,proto3,enum=nrm.FishType" json:"type,omitempty"`
	Location             *Location            `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Fish) Reset()         { *m = Fish{} }
func (m *Fish) String() string { return proto.CompactTextString(m) }
func (*Fish) ProtoMessage()    {}
func (*Fish) Descriptor() ([]byte, []int) {
	return fileDescriptor_7713465e1e636f0d, []int{1}
}

func (m *Fish) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Fish.Unmarshal(m, b)
}
func (m *Fish) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Fish.Marshal(b, m, deterministic)
}
func (m *Fish) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Fish.Merge(m, src)
}
func (m *Fish) XXX_Size() int {
	return xxx_messageInfo_Fish.Size(m)
}
func (m *Fish) XXX_DiscardUnknown() {
	xxx_messageInfo_Fish.DiscardUnknown(m)
}

var xxx_messageInfo_Fish proto.InternalMessageInfo

func (m *Fish) GetWeightKg() int64 {
	if m != nil {
		return m.WeightKg
	}
	return 0
}

func (m *Fish) GetTime() *timestamp.Timestamp {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *Fish) GetType() FishType {
	if m != nil {
		return m.Type
	}
	return FishType_NOT_SPECIFIED
}

func (m *Fish) GetLocation() *Location {
	if m != nil {
		return m.Location
	}
	return nil
}

type Location struct {
	Latitude             float64  `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float64  `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_7713465e1e636f0d, []int{2}
}

func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (m *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(m, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Location) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

// Summary of the storage operation
type StorageSummary struct {
	Success              bool                 `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Attempts             int32                `protobuf:"varint,2,opt,name=attempts,proto3" json:"attempts,omitempty"`
	LastAttemptedAt      *timestamp.Timestamp `protobuf:"bytes,3,opt,name=last_attempted_at,json=lastAttemptedAt,proto3" json:"last_attempted_at,omitempty"`
	FailureMessage       string               `protobuf:"bytes,4,opt,name=failure_message,json=failureMessage,proto3" json:"failure_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *StorageSummary) Reset()         { *m = StorageSummary{} }
func (m *StorageSummary) String() string { return proto.CompactTextString(m) }
func (*StorageSummary) ProtoMessage()    {}
func (*StorageSummary) Descriptor() ([]byte, []int) {
	return fileDescriptor_7713465e1e636f0d, []int{3}
}

func (m *StorageSummary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageSummary.Unmarshal(m, b)
}
func (m *StorageSummary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageSummary.Marshal(b, m, deterministic)
}
func (m *StorageSummary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageSummary.Merge(m, src)
}
func (m *StorageSummary) XXX_Size() int {
	return xxx_messageInfo_StorageSummary.Size(m)
}
func (m *StorageSummary) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageSummary.DiscardUnknown(m)
}

var xxx_messageInfo_StorageSummary proto.InternalMessageInfo

func (m *StorageSummary) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *StorageSummary) GetAttempts() int32 {
	if m != nil {
		return m.Attempts
	}
	return 0
}

func (m *StorageSummary) GetLastAttemptedAt() *timestamp.Timestamp {
	if m != nil {
		return m.LastAttemptedAt
	}
	return nil
}

func (m *StorageSummary) GetFailureMessage() string {
	if m != nil {
		return m.FailureMessage
	}
	return ""
}

func init() {
	proto.RegisterEnum("nrm.FishType", FishType_name, FishType_value)
	proto.RegisterType((*ResourceUpdate)(nil), "nrm.ResourceUpdate")
	proto.RegisterType((*Fish)(nil), "nrm.Fish")
	proto.RegisterType((*Location)(nil), "nrm.Location")
	proto.RegisterType((*StorageSummary)(nil), "nrm.StorageSummary")
}

func init() {
	proto.RegisterFile("protos/fish/fish_capture_management.proto", fileDescriptor_7713465e1e636f0d)
}

var fileDescriptor_7713465e1e636f0d = []byte{
	// 522 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x4f, 0x6f, 0xda, 0x4c,
	0x10, 0xc6, 0x63, 0x6c, 0x82, 0x19, 0xde, 0x10, 0x67, 0xdf, 0x8b, 0x4b, 0x5b, 0x95, 0x72, 0x29,
	0xa9, 0x14, 0x3b, 0xa2, 0x87, 0x9e, 0x09, 0x36, 0x2a, 0x0a, 0x90, 0x6a, 0x81, 0x4b, 0x2f, 0xd6,
	0x62, 0x96, 0xc5, 0xc2, 0xff, 0xb4, 0xbb, 0x56, 0xc5, 0xc7, 0xe9, 0xa7, 0xe8, 0xd7, 0xab, 0xbc,
	0xc6, 0x54, 0xb9, 0xf4, 0x62, 0x79, 0x7e, 0xf3, 0xec, 0xcc, 0xec, 0xb3, 0x03, 0xf7, 0x39, 0xcf,
	0x64, 0x26, 0xdc, 0x7d, 0x24, 0x0e, 0xea, 0x13, 0x84, 0x24, 0x97, 0x05, 0xa7, 0x41, 0x42, 0x52,
	0xc2, 0x68, 0x42, 0x53, 0xe9, 0x28, 0x0d, 0xd2, 0x53, 0x9e, 0xf4, 0x3e, 0xb0, 0x2c, 0x63, 0x31,
	0x75, 0x15, 0xda, 0x16, 0x7b, 0x57, 0x46, 0x09, 0x15, 0x92, 0x24, 0x79, 0xa5, 0x1a, 0xb8, 0xd0,
	0xc5, 0x54, 0x64, 0x05, 0x0f, 0xe9, 0x26, 0xdf, 0x11, 0x49, 0xd1, 0x7b, 0x30, 0xca, 0xc2, 0xb6,
	0xd6, 0xd7, 0x87, 0x9d, 0x51, 0xdb, 0x49, 0x79, 0xe2, 0x4c, 0x23, 0x71, 0xc0, 0x0a, 0x0f, 0x7e,
	0x69, 0x60, 0x94, 0x21, 0x7a, 0x0b, 0xed, 0x9f, 0x34, 0x62, 0x07, 0x19, 0x1c, 0x99, 0xad, 0xf5,
	0xb5, 0xa1, 0x8e, 0xcd, 0x0a, 0x3c, 0x33, 0xe4, 0x80, 0x51, 0x76, 0xb2, 0x1b, 0x7d, 0x6d, 0xd8,
	0x19, 0xf5, 0x9c, 0x6a, 0x0c, 0xa7, 0x1e, 0xc3, 0x59, 0xd7, 0x63, 0x60, 0xa5, 0x43, 0x1f, 0xc1,
	0x90, 0xa7, 0x9c, 0xda, 0x7a, 0x5f, 0x1b, 0x76, 0x47, 0x37, 0x97, 0xa6, 0xeb, 0x53, 0x4e, 0xb1,
	0x4a, 0xa1, 0x7b, 0x30, 0xe3, 0x2c, 0x24, 0x32, 0xca, 0x52, 0xdb, 0x50, 0x65, 0x2b, 0xd9, 0xfc,
	0x0c, 0xf1, 0x25, 0x3d, 0xf0, 0xc0, 0xac, 0x29, 0xea, 0x81, 0x19, 0x13, 0x19, 0xc9, 0x62, 0x47,
	0xd5, 0x94, 0x1a, 0xbe, 0xc4, 0xe8, 0x1d, 0xb4, 0xe3, 0x2c, 0x65, 0x55, 0xb2, 0xa1, 0x92, 0x7f,
	0xc1, 0xe0, 0xb7, 0x06, 0xdd, 0x95, 0xcc, 0x38, 0x61, 0x74, 0x55, 0x24, 0x09, 0xe1, 0x27, 0x64,
	0x43, 0x4b, 0x14, 0x61, 0x48, 0x85, 0x50, 0xb5, 0x4c, 0x5c, 0x87, 0x65, 0x1b, 0x22, 0x25, 0x4d,
	0x72, 0x29, 0x54, 0xa5, 0x26, 0xbe, 0xc4, 0x68, 0x0a, 0x77, 0x31, 0x11, 0x32, 0x38, 0x03, 0xba,
	0x0b, 0x88, 0x54, 0x37, 0xfd, 0xb7, 0x33, 0xb7, 0xe5, 0xa1, 0x71, 0x7d, 0x66, 0x2c, 0xd1, 0x27,
	0xb8, 0xdd, 0x93, 0x28, 0x56, 0xaf, 0x4d, 0x85, 0x20, 0x8c, 0x2a, 0x23, 0xda, 0xb8, 0x7b, 0xc6,
	0x8b, 0x8a, 0x7e, 0x66, 0x60, 0xd6, 0xe6, 0xa1, 0x3b, 0xb8, 0x59, 0xbe, 0xac, 0x83, 0xd5, 0x77,
	0x7f, 0x32, 0x9b, 0xce, 0x7c, 0xcf, 0xba, 0x42, 0xff, 0x81, 0xb9, 0x18, 0x4f, 0x9e, 0x7d, 0xec,
	0xcf, 0x2d, 0x0d, 0x75, 0xa0, 0xb5, 0x1a, 0x63, 0x6f, 0xb6, 0xf4, 0xad, 0x06, 0x6a, 0x81, 0x3e,
	0x79, 0xf1, 0x2c, 0x1d, 0x99, 0x60, 0xac, 0x37, 0xcb, 0xb1, 0x65, 0x94, 0x6a, 0xec, 0x7b, 0x81,
	0x87, 0x37, 0x0b, 0xab, 0x59, 0x46, 0x4f, 0xf3, 0x8d, 0x3f, 0x9d, 0xad, 0xbe, 0x59, 0xd7, 0xa3,
	0x35, 0xbc, 0x59, 0x12, 0x59, 0x70, 0x12, 0xd7, 0x4b, 0xb4, 0xb8, 0xac, 0x21, 0xfa, 0x0a, 0xcd,
	0xd2, 0x3e, 0x8a, 0xfe, 0x57, 0xef, 0xf4, 0x7a, 0xcd, 0x7a, 0x15, 0x7c, 0xed, 0xef, 0xe0, 0x6a,
	0xa8, 0x3d, 0x6a, 0x4f, 0xa3, 0x1f, 0x8f, 0x2c, 0x92, 0x87, 0x62, 0xeb, 0x84, 0x59, 0xe2, 0xa6,
	0xdb, 0x9c, 0xf0, 0x23, 0xe5, 0x6e, 0xca, 0x93, 0x07, 0x2a, 0x0f, 0x0f, 0x61, 0x1c, 0xd1, 0x54,
	0xba, 0xf9, 0x91, 0x55, 0x6b, 0x5d, 0x26, 0xb6, 0xd7, 0xea, 0xf7, 0xcb, 0x9f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x30, 0xbf, 0xfe, 0x06, 0x21, 0x03, 0x00, 0x00,
}
